# Generated by Django 4.1.6 on 2023-02-14 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_title', models.CharField(max_length=20, unique=True, verbose_name='название цвета')),
            ],
            options={
                'verbose_name': 'цвет',
                'verbose_name_plural': 'цвета',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MarkCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_title', models.CharField(max_length=50, unique=True, verbose_name='марка автомобиля')),
            ],
            options={
                'verbose_name': 'марка',
                'verbose_name_plural': 'марки',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ModelCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_title', models.CharField(max_length=50, unique=True, verbose_name='модель автомобиля')),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'модели',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_issue', models.IntegerField(verbose_name='год выпуска')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.colorcar')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.markcar')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.modelcar')),
            ],
            options={
                'verbose_name': 'автомобиль',
                'verbose_name_plural': 'автомобили',
                'ordering': ('-id',),
            },
        ),
    ]
